inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

# テストは describe / context がネストして長くなるのが自然なので、行数制限の対象外にする
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'